[settings]
idiomatic_version_file_enable_tools = [
  "go",
  "node",
  "python",
  "ruby",
]

[tools]
bun = "1"
delta = "latest"
deno = "2"
gh = "latest"
ghq = "latest"
go = "1"
lazydocker = "latest"
lazygit = "latest"
lua = "5.1" # NeoVim0.12に合わせる
lua-language-server = "latest"
neovim = "latest"
nim = {
  version = "latest",
  platforms = {
    linux-arm64 = {
      checksum_url = "https://nim-lang.org/download/nim-{{ version }}-linux_arm64.tar.xz.sha256",
      url = "https://nim-lang.org/download/nim-{{ version }}-linux_arm64.tar.xz"
    },
    linux-x64 = {
      checksum_url = "https://nim-lang.org/download/nim-{{ version }}-linux_x64.tar.xz.sha256",
      url = "https://nim-lang.org/download/nim-{{ version }}-linux_x64.tar.xz"
    }, 
    macos-arm64 = {
      checksum_url = "https://nim-lang.org/download/nim-{{ version }}-macosx_arm64.tar.xz.sha256",
      url = "https://nim-lang.org/download/nim-{{ version }}-macosx_arm64.tar.xz"
    },
    macos-x64 = {
      checksum_url = "https://nim-lang.org/download/nim-{{ version }}-macosx_x64.tar.xz.sha256",
      url = "https://nim-lang.org/download/nim-{{ version }}-macosx_x64.tar.xz"
    },
    windows-arm64 = {
      checksum_url = "https://nim-lang.org/download/nim-{{ version }}_x64.zip.sha256",
      url = "https://nim-lang.org/download/nim-{{ version }}_x64.zip"
    },
    windows-x64 = {
      checksum_url = "https://nim-lang.org/download/nim-{{ version }}_x64.zip.sha256",
      url = "https://nim-lang.org/download/nim-{{ version }}_x64.zip"
    }
  },
  strip_components = 1,
  version_list_url = "https://nim-lang.org/install.html",
  version_regex = 'nim-(\d+\.\d+\.\d+)-linux_x64\.tar\.xz'
}
node = "26"
python = "3.14"
ruby = "4"
ruff = "prefix:0.16"
rust = "latest"
shellcheck = "prefix:0.11"
shfmt = "prefix:3.14"
stylua = "latest"
taplo = "0.10"
tree-sitter = "latest"
uv = "prefix:0.12"
